# Generated by Django 2.2.5 on 2019-09-15 22:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=30)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(default='', max_length=100)),
                ('is_secret', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('html', models.TextField(blank=True, max_length=100000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=30)),
                ('url', models.CharField(default='', max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observer.Site')),
            ],
        ),
    ]
