# Generated by Django 2.2.5 on 2019-09-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='text',
        ),
        migrations.AddField(
            model_name='site',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='version',
            name='html',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
